### ISSUE TITLE
halting-problem used?

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade-attrs#1]
Apparently halting-problem is `require`d but not used anywhere. How would it be used?

**Comment by ForbesLindesay** [comment]
Ah, was going to use it to make sure that we never "toConstant"ed an infinite loop, but I decided instead to just update https://github.com/ForbesLindesay/constantinople to only count things as constant if they are simple expressions (i.e. make it far more restrictive).  An example of something that would cause the current jade compiler to get into an infinite loop, but would compile fine (although admittedly it wouldn't render) with this update would be:

```jade
div(data-foo=(function () { while (true); return 'foo'; }()))
```

We can use halting-problem as part of jade-code-gen to catch this kind of case, but do so in the output code rather than as part of jade-attrs.
